name: eventify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: lib/fonts/JosefinSans-Bold.ttf
